In [1]:
import numpy as np

In [2]:
# arrangeで0-8のList作成、reshapeで3行3列に成形
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# 転置 行列の入れ替え
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [4]:
# transpose関数でも可能
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [5]:
# 軸の順番を指定可能。0軸を行、1軸を列 これは元のArrayと変わらない
arr.transpose((0,1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# 1軸を行、0軸を列とする 転置と同じ状態
arr.transpose((1,0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [7]:
# swapaxesは、どの軸とどの軸を入れ替えるかを指定する。順番は関係ない
arr.swapaxes(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 行列の乗算　転置と元の行列
np.dot(arr.T, arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [11]:
# 3次元行列
arr3 = np.arange(12).reshape((3,2,2))
arr3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [12]:
arr3[0]

array([[0, 1],
       [2, 3]])

In [13]:
arr3[1]

array([[4, 5],
       [6, 7]])

In [14]:
# 3次元行列の転置も可能
arr3.transpose((0,2,1))

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])

In [15]:
arr3.transpose((1,0,2))

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

In [16]:
arr3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [17]:
arr3.transpose((2,1,0))

array([[[ 0,  4,  8],
        [ 2,  6, 10]],

       [[ 1,  5,  9],
        [ 3,  7, 11]]])