In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 平方根
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
# 自然対数の底ｅの累乗 2.71828183
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
# 正規分布に従う乱数をＡに入れる
A = np.random.randn(10)

A

array([ 1.21466921, -0.22452299,  1.51706861,  0.32908581, -0.89772695,
        1.09404447,  0.00913798, -1.15079931, -1.46792625,  1.54929305])

In [6]:
# 正規分布に従う乱数をＢに入れる
B = np.random.randn(10)
B

array([ 0.39269043, -0.61683725, -0.2897499 , -0.92381646, -0.33781677,
        0.4089135 , -1.83553244, -0.75832614,  0.87842   , -1.55402414])

In [7]:
# 2つのアレイの足し算
np.add(A,B)

array([ 1.60735964, -0.84136024,  1.22731871, -0.59473065, -1.23554372,
        1.50295797, -1.82639447, -1.90912545, -0.58950625, -0.00473109])

In [8]:
# 各要素の大きな値を返す
np.maximum(A,B)

array([ 1.21466921, -0.22452299,  1.51706861,  0.32908581, -0.33781677,
        1.09404447,  0.00913798, -0.75832614,  0.87842   ,  1.54929305])

In [9]:
# numpyのドキュメントを開く　Helpメニューからでも参照可能
# import webbrowserによりブラウザをopen可能
# 詳しい関数の説明は公式マニュアルを参照

website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True