In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
# 名前を付けてArrayを保存 (バイナリデータ、拡張子は .npy)
np.save('test_array',arr)

In [5]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 保存したArrayをロード
arr1 = np.load('test_array.npy')
arr1

array([0, 1, 2, 3, 4])

In [7]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Arrayをまとめてzip形式で保存
np.savez('zip_arrays.npz',x=arr1,y=arr2)

In [9]:
# ロード
archive_array = np.load('zip_arrays.npz')
archive_array['x']

array([0, 1, 2, 3, 4])

In [10]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# テキストファイル形式で保存
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('test_text.txt',arr,delimiter=',')
#テキストエディタで確認すると保存内容が見れます

In [12]:
# LinuxやMacであれば以下のcatコマンドを使ってブラウザで確認可能
!cat test_text.txt

'cat' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。


In [13]:
#テキストファイルのロード
arr = np.loadtxt('test_text.txt',delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])