In [1]:
import numpy as np

In [2]:
7/2

3.5

In [3]:
# Array作成
a1 = np.array([[1,2,3,4],[5,6,7,8]])

a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# Array*Array 掛け算
a1*a1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [5]:
# Array-Array 引き算
a1-a1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
# 2をArrayの各要素で割る
2 / a1

array([[2.        , 1.        , 0.66666667, 0.5       ],
       [0.4       , 0.33333333, 0.28571429, 0.25      ]])

In [7]:
# 累乗計算　べき乗
a1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)