In [14]:
# NumpyのArrayを利用 npという名前でimport
import numpy as np

# PythonのListを1つ作成
list1 = [1,2,3,4]

# NumpyのArrayにListを格納して作成
array1 = np.array(list1)

In [15]:
# Arrayを表示するとListが1つ格納されている
array1

array([1, 2, 3, 4])

In [16]:
# 別のListを作成
list2 = [5,6,7,8]

# ListのListを作成
lists = [list1,list2]

# ListのListを、NumpyのArrayに格納すると多次元Arrayができる
array2 = np.array(lists)

array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# Arrayサイズ
array2.shape

(2, 4)

In [18]:
# Arrayのデータ型
array2.dtype

dtype('int32')

In [19]:
# すべての要素が０のArray生成
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
# 名前を付けて格納
zeros_array = np.zeros(5)

In [21]:
# データ型を確認
zeros_array.dtype

dtype('float64')

In [22]:
#すべての要素が1のArray生成
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# 空のArray　値は不定値・・・使い方を誤ると不定値により正しい結果が得られない
np.empty(5)

array([2.12199579e-314, 6.95250701e-310, 5.73116149e-321, 6.95250701e-310,
       0.00000000e+000])

In [24]:
# 以下も同様で表示結果はたまたま0ですが基本は不定値　初期化を忘れない または np.zerosを使う
np.empty((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# Dentity Array 単位行列
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# arange関数 ・・・0から()内の数値の1つ前までの整数でArray生成
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# 初期値,最終値,ステップを指定
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])