In [1]:
import numpy as np

In [2]:
# Arrayをarange関数で生成
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# index(添え字)によるアクセス
arr[5]

5

In [4]:
# index(添え字)による連続アクセス (スライス) (2-7の手前)
arr[2:7]

array([2, 3, 4, 5, 6])

In [5]:
# スライスは代入に利用も可能
arr[0:6]=100

arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [6]:
# 再度0-10にする
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# スライスして切り出す
slice_arr = arr[0:6]

slice_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
# スライスして切り出したArrayを変更　「: 」のみは全ての要素を表す
slice_arr[:]=100
slice_arr

array([100, 100, 100, 100, 100, 100])

In [9]:
# 切り出したArrayではなく、元のArrayを表示
arr
# スライスで切り出した場合は元のデータも書き換わる

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [10]:
# 独立した形でコピーをする場合はcopy関数を利用
arr_copy = arr.copy()

arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [11]:
arr_copy[0:6]=0

arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [13]:
# 多次元ArrayのIndex(添え字)
arr2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# 行
arr2[1]

array([4, 5, 6])

In [15]:
# 行列指定
arr2[1][0]

4

In [16]:
# 行列指定方法2
arr2[1,0]

4

In [17]:
# スライス
arr2[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [18]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [19]:
# 練習 10x10の0Arrayを用意
arr3 = np.zeros((10,10))


In [20]:
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
#Arrayのlength
arr_length = arr3.shape[1]

In [22]:
arr_length

10

In [23]:
for i in range(arr_length):
    arr3[i] = i
    
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [24]:
# 偶数行のみ
arr3[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [25]:
# 順番変更可能
arr3[[9,5,2,4]]

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])