In [1]:
# NumpyのArrayを利用 npという名前でimport
import numpy as np

# PythonのListを1つ作成
list1 = [1,2,3,4]

# NumpyのArrayにListを格納して作成
array1 = np.array(list1)

ModuleNotFoundError: No module named 'numpy'

In [ ]:
# Arrayを表示するとListが1つ格納されている
array1

array([1, 2, 3, 4])

In [ ]:
# 別のListを作成
list2 = [5,6,7,8]

# ListのListを作成
lists = [list1,list2]

# ListのListを、NumpyのArrayに格納すると多次元Arrayができる
array2 = np.array(lists)

array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Arrayサイズ
array2.shape

(2, 4)

In [ ]:
# Arrayのデータ型
array2.dtype

dtype('int32')

In [ ]:
# すべての要素が０のArray生成
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# 名前を付けて格納
zeros_array = np.zeros(5)

In [ ]:
# データ型を確認
zeros_array.dtype

dtype('float64')

In [ ]:
#すべての要素が1のArray生成
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 空のArray　値は不定値・・・使い方を誤ると不定値により正しい結果が得られない
np.empty(5)

array([2.12199579e-314, 7.22756602e+159, 6.46237865e-321, 5.05034999e-312,
       1.50762024e+161])

In [ ]:
# 以下も同様で表示結果はたまたま0ですが基本は不定値　初期化を忘れない または np.zerosを使う
np.empty((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Dentity Array 単位行列
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# arange関数 ・・・0から()内の数値の1つ前までの整数でArray生成
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 初期値,最終値,ステップを指定
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])